//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.31 at 08:11:52 PM COT 
//


package com.parameta.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.parameta.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.parameta.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetEmpleadosRequest }
     * 
     */
    public GetEmpleadosRequest createGetEmpleadosRequest() {
        return new GetEmpleadosRequest();
    }

    /**
     * Create an instance of {@link GetEmpleadosResponse }
     * 
     */
    public GetEmpleadosResponse createGetEmpleadosResponse() {
        return new GetEmpleadosResponse();
    }

    /**
     * Create an instance of {@link Empleado }
     * 
     */
    public Empleado createEmpleado() {
        return new Empleado();
    }

    /**
     * Create an instance of {@link GetEmpleadoRequest }
     * 
     */
    public GetEmpleadoRequest createGetEmpleadoRequest() {
        return new GetEmpleadoRequest();
    }

    /**
     * Create an instance of {@link GetEmpleadoResponse }
     * 
     */
    public GetEmpleadoResponse createGetEmpleadoResponse() {
        return new GetEmpleadoResponse();
    }

    /**
     * Create an instance of {@link PostEmpleadoRequest }
     * 
     */
    public PostEmpleadoRequest createPostEmpleadoRequest() {
        return new PostEmpleadoRequest();
    }

    /**
     * Create an instance of {@link PostEmpleadoResponse }
     * 
     */
    public PostEmpleadoResponse createPostEmpleadoResponse() {
        return new PostEmpleadoResponse();
    }

}
